### ISSUE TITLE
Adopting regex-tdfa

### ISSUE THREAD

**Issue by neongreen** [haskell-hvr/regex-base#1]
@hvr I am the current maintainer of regex-tdfa. Since most other `regex-` packages are under your wing now, would you like to adopt regex-tdfa as well? I doubt it would actually increase the maintenance burden, especially since the whole `regex-` ecosystem would be able to live in a single repo.

**Comment by hvr** [comment]
@neongreen I'd be happy to adopt `regex-tdfa` as well if you want to get it off your hands :-)

But I'd still prefer to keep it in individual repos (possibly with an additional meta/mega-repo for CI purposes) as it avoids the usual awkwardness with unrelated histories being conflated with branching & tagging due to the way Git is designed to operate.

**Comment by neongreen** [comment]
> if you want to get it off your hands

I certainly do.

As of now, you have maintainer rights on Hackage. Unfortunately, I can not transfer https://github.com/ChrisKuklewicz/regex-tdfa to you. Ping me when you create a regex-tdfa repo at haskell-hvr, and I will transfer the issues there.

**Comment by hvr** [comment]
@neongreen ping :-) (see also https://github.com/haskell-hvr/regex-tdfa/invitations)

**Comment by neongreen** [comment]
Can you also enable issues for haskell-hvr/regex-tdfa?

(Also, I'm going to be afk until Oct 18.)

**Comment by hvr** [comment]
@neongreen fixed! didn't notice this would happen if I merely `fork` a repo

**Comment by hvr** [comment]
@neongreen ping? :-)

**Comment by neongreen** [comment]
I was afk until yesterday. Will hopefully look over the weekend.

**Comment by neongreen** [comment]
Done.
